import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: {};
};

export default function RootLayout(props: Props) {
  return (
    <html lang='en'>
      <body className={`${inter.className}  border-green-500 border-2 m-1`}>
        <h4 className='px-2'>Root Layout</h4>
        {props.children}
      </body>
    </html>
  );
}
