import './globals.css';
import Footer from '@/ui/footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='[&>*:not(:first-child)]:mx-2 h-screen'>
        <nav className='h-10 mb-4 p-2 bg-slate-100 mx-0 text-black'>
          <h1>My Navbar</h1>
        </nav>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
