import './globals.css';
import NavBar from '@/ui/navbar';
import Footer from '@/ui/footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      {/* '[&>*:not(:first-child)]:mx-2 h-screen' */}
      <body>
        <NavBar />
        <main className='p-3'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
